<img src='letscodebr_cover.jpeg' align='left' width=100%/>

# Ada Tech [DS-PY-004] Técnicas de Programação I (PY) Aula 2 : Numpy - Resolução do Exercício 1.

A ideia dessa prática é exercitar os pontos de que vamos precisar para resolver o desafio. Usaremos um resumo do conjunto de dados [Kaggle](https://www.kaggle.com/kyanyoga/sample-sales-data) que contém dados de vendas:

## Exercício 1

Leia os dados do arquivo `../Data/sales_data_sample_excercise.csv`, que contém alguns dados numéricos e alguns tipos de `string` de caracteres. A amostra contém dados de vendas, informações do pedido, vendas, cliente, remessa, etc., usados para segmentação, análise do cliente, clustering e outros. 


As colunas são:

* `ORDERNUMBER`: `int`, id da orden de pedido

* `SALES`: `float`, quantia paga

* `MONTH_ID`: `int`, mês

* `YEAR_ID`: `int`, ano

* `PRODUCTLINE`: `str`, produto

* `COUNTRY`: `str`, país de venda

Lembre-se de que todos os elementos de uma instância `ndarray` devem ser do mesmo tipo. Portanto, vamos ler o arquivo e criar uma instância de `ndarray` do tipo `string`.

O que aconteceria se tentássemos criar uma instância do tipo `int`? E do tipo `float`?

In [1]:
import numpy as np

# local:
data_location = '../Data/sales_data_sample_excercise.csv'

In [2]:
data_type_default = np.genfromtxt(data_location, 
                                  skip_header = 1, 
                                  delimiter = '\t'
                                 )
data_type_default

array([[1.01070e+04, 2.87100e+03, 2.00000e+00, 2.00300e+03,         nan,
                nan],
       [1.01210e+04, 2.76590e+03, 5.00000e+00, 2.00300e+03,         nan,
                nan],
       [1.01340e+04, 3.88434e+03, 7.00000e+00, 2.00300e+03,         nan,
                nan],
       ...,
       [1.03860e+04, 5.41757e+03, 3.00000e+00, 2.00500e+03,         nan,
                nan],
       [1.03970e+04, 2.11616e+03, 3.00000e+00, 2.00500e+03,         nan,
                nan],
       [1.04140e+04, 3.07944e+03, 5.00000e+00, 2.00500e+03,         nan,
                nan]])

In [3]:
data_type_str = np.genfromtxt(data_location, 
                              skip_header = 1, 
                              delimiter = '\t', 
                              dtype = str
                             )
data_type_str

array([['10107', '2871', '2', '2003', 'Motorcycles', 'USA'],
       ['10121', '2765.9', '5', '2003', 'Motorcycles', 'France'],
       ['10134', '3884.34', '7', '2003', 'Motorcycles', 'France'],
       ...,
       ['10386', '5417.57', '3', '2005', 'Ships', 'Spain'],
       ['10397', '2116.16', '3', '2005', 'Ships', 'France'],
       ['10414', '3079.44', '5', '2005', 'Ships', 'USA']], dtype='<U16')

In [4]:
data_type_int = np.genfromtxt(data_location, 
                              skip_header = 1, 
                              delimiter = '\t', 
                              dtype = int
                             )
data_type_int

array([[10107,  2871,     2,  2003,    -1,    -1],
       [10121,    -1,     5,  2003,    -1,    -1],
       [10134,    -1,     7,  2003,    -1,    -1],
       ...,
       [10386,    -1,     3,  2005,    -1,    -1],
       [10397,    -1,     3,  2005,    -1,    -1],
       [10414,    -1,     5,  2005,    -1,    -1]])

In [5]:
data_type_float = np.genfromtxt(data_location, 
                                skip_header = 1, 
                                delimiter = '\t', 
                                dtype = float
                               )
data_type_float

array([[1.01070e+04, 2.87100e+03, 2.00000e+00, 2.00300e+03,         nan,
                nan],
       [1.01210e+04, 2.76590e+03, 5.00000e+00, 2.00300e+03,         nan,
                nan],
       [1.01340e+04, 3.88434e+03, 7.00000e+00, 2.00300e+03,         nan,
                nan],
       ...,
       [1.03860e+04, 5.41757e+03, 3.00000e+00, 2.00500e+03,         nan,
                nan],
       [1.03970e+04, 2.11616e+03, 3.00000e+00, 2.00500e+03,         nan,
                nan],
       [1.04140e+04, 3.07944e+03, 5.00000e+00, 2.00500e+03,         nan,
                nan]])

# Exercício 2 - Tipos

Crie um arranjo de [tipo](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.astype.html) numérico `float` que tenha a coluna `SALES` como valores e outro arranjo de tipo caracteres `str` que tenha a coluna `COUNTRY` como valores.

In [6]:
data = np.genfromtxt(data_location, 
                     skip_header = 1, 
                     delimiter = '\t', 
                     dtype = str
                    )

sales_vector_str = data[:, 1]
sales_vector =  sales_vector_str.astype(float)
print(sales_vector)

country_vector = data[ : , 5]
print(country_vector)

[2871.   2765.9  3884.34 ... 5417.57 2116.16 3079.44]
['USA' 'France' 'France' ... 'Spain' 'France' 'USA']


In [7]:
sales_vector_str

array(['2871', '2765.9', '3884.34', ..., '5417.57', '2116.16', '3079.44'],
      dtype='<U16')

## Exercício 3 - Funções de agregação

Sobre os dados de preço de venda, na coluna `SALES`, calcule os valores [estatísticos](https://numpy.org/doc/stable/reference/routines.statistics.html):

* Mínimo

* Máximo

* Média

* Quantidade

* soma

In [8]:
np.min(sales_vector)

482.13

In [9]:
np.max(sales_vector)

14082.8

In [10]:
np.average(sales_vector)

3553.889071909316

In [11]:
sales_vector.size

2823

In [12]:
np.sum(sales_vector)

10032628.85

## Exercício 4 - Indexing

a) Quantas vendas foram realizadas nos EUA?.

Dica: indexação booleana.

b) Quais são os preços das $5$ vendas que estão nas linhas $6$ a $10$ do conjunto de dados?

Vamos resolver usando o fatiamento (sliceing) do arranjo e a indexação sofisticada ([fancy indexing](https://docs.python.org/3/library/functions.html#func-range)).

In [13]:
print(country_vector)

mask = country_vector == 'USA'
print(mask)

country_vector_USA = country_vector[mask]
country_vector_USA.size

['USA' 'France' 'France' ... 'Spain' 'France' 'USA']
[ True False False ... False False  True]


1004

In [14]:
# array slicing:
sales_vector_slicing = sales_vector[6 : 11]

print(sales_vector_slicing)

[2497.77 5512.32 2168.54 4708.44 3965.66]


Observe que o limite superior não está incluído.

In [15]:
# fancy indexing

indexes = range(6, 11, 1)
indexes_int = [6, 7, 8, 9, 10]
sales_vector_fancy = sales_vector[indexes_int]

print(sales_vector_fancy)

[2497.77 5512.32 2168.54 4708.44 3965.66]


Obtemos o mesmo resultado com uma ou outra forma de indexação:

- uma maneira é comparar os dois arranjos elemento por elemento:

In [16]:
print(sales_vector_slicing == sales_vector_fancy)

[ True  True  True  True  True]


Outra maneira é ver se o número de elementos que são iguais nos dois arranjos 
```python
python(sum(sales_vector_slicing == sales_vector_fancy))
``` 
é igual ao número total de elementos por arranjo.

In [17]:
cant_elem = len(sales_vector_slicing)
print(sum(sales_vector_slicing == sales_vector_fancy) == cant_elem)

True


E outra maneira é ver se não há elemento diferente, ou seja, negar qualquer:

In [18]:
print(not any(sales_vector_slicing != sales_vector_fancy))

True
