<img src='letscodebr_cover.jpeg' align='left' width=100%/>

# Ada Tech [DS-PY-004] Técnicas de Programação I (PY) Aula 2 : Numpy 1.

## Numpy Array

<a id="section_intro"></a> 
###  Intro

Um [arranjo](https://machinelearningmastery.com/gentle-introduction-n-dimensional-arrays-python-numpy/) é uma estrutura de dados que permite agrupar vários valores ou elementos em uma única variável (um único nome).

Os elementos de um arranjo são todos do mesmo tipo (ao contrário das listas Python).

Matrizes unidimensionais e bidimensionais têm nomes próprios:

* uma matriz unidimensional é um **vetor**

* uma matriz bidimensional é uma **tabela** ou **matriz**

Matrizes de três ou mais dimensões são chamadas de [n-dimensionais](https://numpy.org/doc/stable/reference/arrays.ndarray.html).

<img src='img/numpy.jpg' align='left' width=50%/>
---

<a id="section_constructor"></a> 
### Construtor

Vamos começar criando arranjos com a função [`numpy.array`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.array.html), a maneira mais simples de [construir](https://numpy.org/doc/stable/user/basics.creation.html) uma arranjo é usar o construtor com um único parâmetro `numpy.array(objeto)`, onde 'objeto' é uma coleção de elementos.

Vejamos un exemplo:

In [1]:
import numpy as np

In [2]:
# Lista de python
python_list = [1, 4, 2, 5, 3]

# Arranjo (array) de inteiros instanciados de uma lista:
my_numpy_array = np.array(python_list)

# Imprimimos o arranjo numpy criado
print(my_numpy_array)

[1 4 2 5 3]


<a id="section_metodos_creacion"></a> 
### Métodos para a criação de arranjos

Existem algumas [rotinas](https://docs.scipy.org/doc/numpy/reference/routines.array-creation.html) de criação de arranjos.  

A biblioteca [Numpy](https://numpy.org/) fornece [métodos](https://towardsdatascience.com/the-ten-best-ways-to-create-numpy-arrays-8b1029a972a7) para criar e inicializar matrizes com certas características.

[Podemos](https://medium.com/ensina-ai/entendendo-a-biblioteca-numpy-4858fde63355) criar matrizes vazias, de zeros, de uns, com uma sequência, de valores aleatórios, de valores que seguem uma determinada distribuição.

A seguir vamos ver um exemplo de alguns deles.

<a id="section_metodos_creacion_empty"></a> 
#### Arranjo vazio

Podemos criar um arranjo vazio com a função [`numpy.empty`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.empty.html), que retorna um novo arranjo com a forma e o tipo fornecidos, sem inicializar as entradas.

Recebe como parâmetros: as dimensões do arranjo a ser criado como uma tupla e o tipo de dados de seus elementos.

Retorna uma nova matriz com as dimensões especificadas na tupla, que é o primeiro parâmetro, **sem inicializar seus elementos**: 

`numpy.empty (shape, dtype = float)`.

In [3]:
np.empty((2, 2), 
         dtype = int
        )

array([[0, 0],
       [0, 0]])

In [4]:
np.empty((3, 1), 
         dtype = float
        )

array([[3.],
       [2.],
       [1.]])

In [5]:
np.empty((1, 3), 
         dtype = bool
        )

array([[ True,  True,  True]])

Qual elemento da tupla indica o número de linhas?

<a id="section_metodos_creacion_zeros"></a> 
#### Arranjos de zeros

Veremos como instanciar um arranjo de zeros com as dimensões especificadas, usaremos o método [`numpy.zeros`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.zeros.html#numpy.zeros), que retorna um novo arranjo de forma e tipo fornecidos, preenchida com zeros.

Recebe como parâmetros: as dimensões do arranjo a ser criado como uma tupla e o tipo de dados de seus elementos: `numpy.zeros (shape, dtype = float)`.

In [6]:
np.zeros(10, 
         dtype = int
        )

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
np.zeros((10, 2), 
         dtype = float
        )

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [8]:
np.zeros((10, 2), 
         dtype = str
        )

array([['', ''],
       ['', ''],
       ['', ''],
       ['', ''],
       ['', ''],
       ['', ''],
       ['', ''],
       ['', ''],
       ['', ''],
       ['', '']], dtype='<U1')

Observe as diferenças nos resultados das duas últimas instruções, onde apenas mudamos o tipo de dados dos elementos do arranjo.

Instanciamos um objeto `dtype`:

In [9]:
dt_array_item = np.dtype('<U1')

Com `dt_array_item.type` vemos o tipo usado para instanciar o `dt_array_item`.

In [10]:
dt_array_item.type

numpy.str_

Portanto, dtype = '<U1' indica que os itens do arranjo de resultados são do tipo `numpy.str_` (string de caracteres)

<a id="section_metodos_creacion_ones"></a> 
#### Arranjo de uns

Agora veremos como instanciar um arranjo de uma das dimensões especificadas.

O método [`numpy.ones`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html) retorna um arranjo de dado formato e tipo, preenchida com uns.

Recebe como parâmetros: as dimensões do arranjo a ser criado como uma tupla e o tipo de dados de seus elementos: `numpy.ones(shape, dtype=float)`

In [11]:
np.ones((10, 2), 
        dtype = int
       )

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [12]:
np.ones((10, 2), 
        dtype = float
       )

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [13]:
np.ones((10, 2), 
        dtype = str
       )

array([['1', '1'],
       ['1', '1'],
       ['1', '1'],
       ['1', '1'],
       ['1', '1'],
       ['1', '1'],
       ['1', '1'],
       ['1', '1'],
       ['1', '1'],
       ['1', '1']], dtype='<U1')

Observe as diferenças nos três resultados, onde apenas alteramos o tipo de dados dos elementos do arranjo.

<a id="section_metodos_creacion_normal"></a> 
#### Arranjo de valores aleatórios com distribuição normal

Agora veremos como instanciar um arranjo de números aleatórios que segue uma distribuição normal.

Usaremos as funções [`Random sampling (numpy.random)`](https://docs.scipy.org/doc/numpy/reference/random/index.html), [`Random Generator`](https://docs.scipy.org/doc/numpy/reference/random/generator.html) e [`random.Generator.normal()`](https://docs.scipy.org/doc/numpy/reference/random/generated/numpy.random.Generator.normal.html#numpy.random.Generator.normal), para gerar valores aleatórios.

O método que gera números aleatórios com distribuição normal recebe como parâmetros: a média, o desvio padrão e as dimensões do arranjo de saída:

`Generator.normal(loc=0.0, scale=1.0, size=None)`

Criamos uma instância do [`Generator`](https://albertcthomas.github.io/good-practices-random-number-generators/) padrão:

In [14]:
random_generator = np.random.default_rng()

Agora geramos 12 números com distribuição normal de média $0$ e desvio padrão $1$:

In [15]:
random_generator.normal(loc = 0, 
                        scale = 1, 
                        size = 12
                       )

array([-0.6518468 ,  1.02741135,  0.61698577,  2.13851497,  0.34250437,
        0.29270536, -0.4475033 , -0.94719772,  0.53319594, -0.09832667,
        0.46402386, -0.48389159])

Agora geramos uma matriz de $16$ linhas e $4$ colunas com números com distribuição normal de média $0$ e desvio padrão $1$:

In [16]:
random_generator.normal(0, 1, size = (16, 4))

array([[-1.34658297e+00,  1.11675716e-01, -1.45097314e+00,
        -9.97208458e-01],
       [-1.11527385e-01, -9.39701060e-01, -5.67268693e-01,
        -5.42989502e-01],
       [-1.77012122e+00, -1.31306864e+00,  2.77160082e-01,
        -6.21207921e-01],
       [-7.92702968e-01,  1.74731511e+00, -4.41653882e-01,
        -1.51601632e-01],
       [ 6.12829006e-01, -2.79684068e+00, -1.68007299e-01,
        -8.70438432e-01],
       [ 8.76374217e-01, -6.05648501e-01,  4.54898296e-01,
         1.74329508e-01],
       [ 6.09998677e-01, -6.24880330e-01,  9.71616940e-01,
         1.16009546e+00],
       [-4.02139737e-01, -4.54857640e-01,  1.71255121e+00,
        -8.61619302e-01],
       [-8.01946369e-01, -8.47148511e-01,  7.15962739e-01,
        -1.54301459e+00],
       [ 1.19886739e+00,  4.45695556e-01,  6.81794988e-01,
        -8.19070161e-01],
       [ 9.92375012e-01, -1.31067495e+00,  3.36184446e-02,
         1.79992816e+00],
       [ 6.02924109e-01,  4.29872146e-01, -2.09001223e-03,
      

Observe que cada vez que executamos esta linha `random_generator.normal (loc = 0, scale = 1, size = 12)` obtemos valores diferentes para os elementos do arranjo.

Tente executá-lo três ou quatro vezes ...

O mesmo ocorre coo `random_generator.normal(0, 1, size = (16,4))`.

Se quisermos obter o mesmo resultado em todas as execuções, devemos inicializar a semente do gerador de números aleatórios.

Para isso, inicializamos a instância `Generator` com um [semente](https://www.sharpsightlabs.com/blog/numpy-random-seed/) qualquer, mas fixa:

In [17]:
seed_cualquier_numero = 2843
random_generator_seed = np.random.default_rng(seed_cualquier_numero)

E agora vamos executar as mesmas linhas que testamos acima várias vezes, usando o objeto `random_generator_seed` inicializado com uma determinada semente:

In [18]:
random_generator_seed = np.random.default_rng(seed_cualquier_numero)
random_generator_seed.normal(loc = 0, 
                             scale = 1, 
                             size = 12
                            )

array([ 0.770969  ,  0.33288743, -0.7145752 ,  0.05428423, -1.44839055,
        0.05562249,  0.04235933, -1.06432701,  3.23668651, -2.61427606,
        0.17057975, -0.11374496])

In [19]:
random_generator_seed = np.random.default_rng(seed_cualquier_numero)
random_generator_seed.normal(0, 1, size = (16, 4))

array([[ 0.770969  ,  0.33288743, -0.7145752 ,  0.05428423],
       [-1.44839055,  0.05562249,  0.04235933, -1.06432701],
       [ 3.23668651, -2.61427606,  0.17057975, -0.11374496],
       [ 1.5431114 , -0.2433953 ,  0.54422367,  0.83475881],
       [ 0.04301992, -0.63558257, -0.16046816,  1.64470349],
       [ 1.33297402, -0.99626982, -1.29590249, -0.61893616],
       [-0.22066461,  0.22727611, -1.38125624,  0.04929038],
       [ 0.63748133, -0.19561326,  0.5938797 ,  1.53733473],
       [-0.27605803,  0.16768242,  0.44111193, -0.07839599],
       [ 0.98677009,  0.94900021, -1.19024724, -0.91697433],
       [-0.62741927,  2.1939412 , -1.0684962 , -1.79228955],
       [ 1.07398541,  1.96988692,  0.3815075 , -0.52205868],
       [ 1.33797156, -0.65238485, -0.74753246,  0.20865684],
       [ 0.99353863,  1.16058088,  1.36554724,  0.07186766],
       [ 1.79045939, -2.00201905, -0.5718638 ,  0.69506072],
       [-0.06683168, -0.74753465, -0.7760167 ,  0.4493421 ]])

Você notou que agora **não muda** o resultado em cada execução?

<a id="section_atributos"></a> 
### Atributos

Vamos estudar alguns [atributos](https://docs.scipy.org/doc/numpy/reference/arrays.ndarray.html#array-attributes) dos arranjos Numpy.

Vamos agora ver exemplos de [atributos](https://www.tutorialspoint.com/numpy/numpy_array_attributes.htm) de um arranjo tridimensional, com números aleatórios de distribuição uniforme de tamanho 3 * 4 * 5

Usaremos um [generador](https://docs.scipy.org/doc/numpy/reference/random/generated/numpy.random.Generator.uniform.html#numpy.random.Generator.uniform) de números aleatórios com distribuição uniforme:

In [20]:
random_generator_seed = np.random.default_rng(seed_cualquier_numero)

low = 10 #inclui o limite inferior
high = 50 # não inclui o limite superior
size = (3, 4, 5)

array_3D = random_generator_seed.uniform(low, high, size)
array_3D

array([[[32.88947629, 16.94855803, 42.83670351, 30.25105684,
         28.20491852],
        [25.18521523, 40.18344021, 34.34396248, 49.42877817,
         25.9067247 ],
        [49.96435545, 39.05367532, 25.72967186, 40.81169652,
         14.0724828 ],
        [41.55501295, 21.67492545, 22.49339028, 25.49163559,
         26.50349253]],

       [[40.72705982, 28.63930892, 18.02914832, 27.35671068,
         38.97125442],
        [16.66917961, 46.25005127, 30.72094445, 48.47205286,
         15.6034732 ],
        [11.79424167, 40.67551164, 21.90868009, 19.00439909,
         23.67958317],
        [10.55338987, 35.92638548, 15.26580613, 12.67264131,
         37.95862821]],

       [[24.33023875, 49.46354377, 48.15236324, 14.74696516,
         23.94498762],
        [19.34227574, 12.22724432, 13.35657914, 42.88661071,
         26.11646608],
        [29.62041973, 17.17235157, 36.46619752, 31.23546738,
         17.94252221],
        [38.58722823, 19.18467869, 35.2361267 , 34.25595785,
         28

<a id="section_atributos_ndim"></a> 
#### ndim

O atributo `.ndim` fornece o número de dimensões do arranjo.

In [21]:
array_3D.ndim

3

<a id="section_atributos_shape"></a> 
#### shape

O atributo `.shape` retorna uma tupla com as dimensões do arranjo.

In [22]:
array_3D.shape

(3, 4, 5)

In [23]:
type(array_3D.shape)

tuple

> Observação: `len(array_3D.shape) == array_3D.ndim`

<a id="section_atributos_size"></a> 
#### size

O atributo `.size` retorna a quantidade de elementos no arranjo.

In [24]:
array_3D.size

60

> Observação: `np.prod(array_3D.shape) == array_3D.size`
>
> `np.prod` multiplica todos os elementos na tupla

<a id="section_atributos_dtype"></a> 
#### dtype

O atributo `.dtype` nos mostra o tipo de dados dos elementos que compõem o arranjo.

In [25]:
array_3D.dtype

dtype('float64')

<a id="section_indexing"></a> 
### Indexing

Um problema comum é o de selecionar os elementos de um arranjo, criteriosamente. Chamamos de ["indexação"](https://numpy.org/doc/stable/user/basics.indexing.html) a operação que resolve o problema de acesso aos elementos de um arranjo.

Selecionar criteriosamente os elementos de um arranjo é o problema resolvido pela [indexação](https://numpy.org/devdocs/user/basics.indexing.html), que reconhece os elementos de um arranjo de acordo com critérios aplicados. Existem três tipos de [indexação](https://towardsdatascience.com/numpy-indexing-explained-c376abb2440d) no Numpy:


* **Array Slicing**: Acessamos os elementos com os parâmetros start, stop, step: `my_array [0: 5: -1]`.

* **Fancy Indexing**: Criamos uma lista de índices e a usamos para acessar certos elementos do arranjo: `my_array[[3,5,7,8]]`.

* **Boolean Indexing**: criamos uma "máscara booleana" (um arranjo ou lista de `True` e `False`) para acessar certos elementos: `my_array[my_array > 4]`.

<a id="section_indexing_slicing"></a>
#### Array Slicing 

##### Slicing sobre uma dimensão

O [slicing](https://wbuchmueller.medium.com/numpys-indexing-and-slicing-notation-explained-visually-67dc981c22c1) (fatiamento) é semelhante às listas python `[start: stop: step]`.

O índice `stop` não está incluído, mas o `start` está incluído. Por exemplo, `[1 : 3]` inclui o índice $1$, mas não $3$. Funciona como um intervalo semifechado $[1 , 3)$.


<img src='img/numpy_indexing.jpg' align='center' width=40%/>

Vejamos alguns exemplos:

Criamos uma arranjo unidimensional usando o método [`np.arange`](https://numpy.org/doc/stable/reference/generated/numpy.arange.html) que retorna valores uniformemente espaçados dentro de um determinado intervalo.

Um arranjo unidimensional com números inteiros entre $0$ e $9$:

In [26]:
one_d_array = np.arange(10)
one_d_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

- Start = $1$:  Começamos pelo segundo elemento
- Stop: Não está definido, então corremos até o final.
- Step: O passo ou distância entre os elementos é $2$.

In [27]:
one_d_array[1 : : 2]  

array([1, 3, 5, 7, 9])

- Start: Não está definido, então començamos desde o primero.
- Stop: Não está definido, então chegamos até o final.
- Step = $-1$, para inverter a ordem do arranjo

In [28]:

one_d_array[ : : -1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

Se quisermos fazer slicing em ordem invertida.

In [29]:
one_d_array[7 : 2 : -1]  

array([7, 6, 5, 4, 3])

##### Slicing sobre arranjos de mais dimensões

Quando temos mais de uma dimensão, podemos [fatiar](https://machinelearningmastery.com/index-slice-reshape-numpy-arrays-machine-learning-python/) cada uma delas separando-as com uma vírgula.

Vejamos alguns exemplos:

In [30]:
random_generator_seed = np.random.default_rng(seed_cualquier_numero)

low = 0 #inclui o limite inferior
high = 10 # não inclui o límite superior
size = (3, 4)

two_d_array = random_generator_seed.uniform(low, high, size)
two_d_array

array([[5.72236907, 1.73713951, 8.20917588, 5.06276421],
       [4.55122963, 3.79630381, 7.54586005, 6.08599062],
       [9.85719454, 3.97668117, 9.99108886, 7.26341883]])

Os dois pontos (`:`) indicam que acessamos todos os elementos de cada linha e o zero após a vírgula indica que só fazemos isso para a coluna $0$ (a primeira).

In [31]:
two_d_array[ : , 0]

array([5.72236907, 4.55122963, 9.85719454])

Acessamos a terceira linha.

In [32]:
two_d_array[ 2, : ]

array([9.85719454, 3.97668117, 9.99108886, 7.26341883])

Outra forma de acessar a terceira linha.

In [33]:
two_d_array[2]

array([9.85719454, 3.97668117, 9.99108886, 7.26341883])

Todas as linhas, uma fatia da segunda e terceira colunas (índices $1$ e $2$).

In [34]:
two_d_array[ : , 1 : 3]

array([[1.73713951, 8.20917588],
       [3.79630381, 7.54586005],
       [3.97668117, 9.99108886]])

Para termos todas as linhas e todas as colunas listadas em ordem reversa.

In [35]:
two_d_array[:, : : -1]

array([[5.06276421, 8.20917588, 1.73713951, 5.72236907],
       [6.08599062, 7.54586005, 3.79630381, 4.55122963],
       [7.26341883, 9.99108886, 3.97668117, 9.85719454]])


<a id="section_indexing_fancy"></a> 
#### Fancy Indexing

Esta [técnica](https://junaidsqazi.medium.com/a6-numpy-part-2-indexing-slicing-broadcasting-fancy-indexing-boolean-masking-universal-d85610eccfe7) consiste em gerar listas que contêm os índices dos elementos que queremos selecionar e utilizar essas listas para indexar.

Vejamos alguns exemplos:

Mantemos todas as colunas e linhas $1, 3, 2$ e repetimos $1$ (índices $0, 2, 1, 0$).

In [36]:
lista_indices_filas = [0, 2, 1, 0]

two_d_array[lista_indices_filas]

array([[5.72236907, 1.73713951, 8.20917588, 5.06276421],
       [9.85719454, 3.97668117, 9.99108886, 7.26341883],
       [4.55122963, 3.79630381, 7.54586005, 6.08599062],
       [5.72236907, 1.73713951, 8.20917588, 5.06276421]])

Ficamos com todas as linhas e colunas $3, 4, 2$ e voltamos para $3$ (índices $2, 3, 1, 2$).

In [37]:
lista_indices_columnas = [2, 3, 1, 2]

two_d_array[:, lista_indices_columnas]

array([[8.20917588, 5.06276421, 1.73713951, 8.20917588],
       [7.54586005, 6.08599062, 3.79630381, 7.54586005],
       [9.99108886, 7.26341883, 3.97668117, 9.99108886]])

E agora selecionamos linhas e colunas, combinando os dois casos anteriores.

In [38]:
two_d_array[lista_indices_filas, lista_indices_columnas]

array([8.20917588, 7.26341883, 3.79630381, 8.20917588])

Vamos observar que ao passar as duas listas, estamos selecionando os elementos
$(0, 2), (2, 3), (1, 1) e (0, 2)$.

É verdade que: 

```python
index_elem_i = (list_indices_files [i], list_indices_columns [i])
```

<a id="section_indexing_boolean"></a> 
#### Boolean Indexing

Esta [técnica](https://www.python-course.eu/numpy_masking.php) é baseada na criação de uma ["máscara booleana"](https://jakevdp.github.io/PythonDataScienceHandbook/02.06-boolean-arrays-and-masks.html), que é uma lista de valores True e False que é usada para selecionar apenas os elementos cujo índice corresponde a um valor True.

Vamos ver alguns exemplos sobre `two_d_array`:

In [39]:
two_d_array

array([[5.72236907, 1.73713951, 8.20917588, 5.06276421],
       [4.55122963, 3.79630381, 7.54586005, 6.08599062],
       [9.85719454, 3.97668117, 9.99108886, 7.26341883]])

Vamos selecionar os elementos maiores que $5$. Para esses, criamos uma máscara com essa condição:

In [40]:
mask_great_5 = two_d_array > 5
mask_great_5

array([[ True, False,  True,  True],
       [False, False,  True,  True],
       [ True, False,  True,  True]])

A máscara tem um valor `True` nos elementos de `two_d_array` com valor maior que $5$ e `False` naqueles com valor menor ou igual a $5$.

Agora vamos usar essa máscara para selecionar os elementos que atendem a essa condição, ou seja, aqueles que têm um valor `True` na máscara:

In [41]:
two_d_array[mask_great_5]

array([5.72236907, 8.20917588, 5.06276421, 7.54586005, 6.08599062,
       9.85719454, 9.99108886, 7.26341883])

Agora vamos definir uma condição mais complexa: vamos selecionar os elementos maiores que $5$ e menores que $8$.

In [42]:
mask_great_5_less_8 = (two_d_array > 5) & (two_d_array < 8)
mask_great_5_less_8

array([[ True, False, False,  True],
       [False, False,  True,  True],
       [False, False, False,  True]])

Agora vamos usar essa máscara para selecionar os elementos que atendem a essa condição, ou seja, aqueles que têm um valor `True` na máscara:

In [43]:
two_d_array[mask_great_5_less_8]

array([5.72236907, 5.06276421, 7.54586005, 6.08599062, 7.26341883])

Como podemos ver, a dificuldade da seleção está na definição da máscara, que pode ser bastante complexa. Mas, depois de calculado, o filtro é idêntico, independentemente do número de condições envolvidas em sua definição e da dimensão do arranjo a ser filtrado

In [44]:
def precipitation(data):
    # modificar aquí:
    result = None
    return result

def quant_days_no_rain(precip):
    # modificar aquí:
    result = 7
    return result

def quant_days_with_rain(precip):
    # modificar aquí:
    result = 7
    return result

def quant_days_vith_rain_greater_100(precip):
    # modificar aquí:
    result = 7
    return result

def quant_days_vith_rain_LessEqual_100(precip):
    # modificar aquí:
    result = 7
    return result


In [45]:
import numpy as np
import os.path

data_location = os.path.abspath('../Data/Seattle2014.csv')

data = np.genfromtxt(data_location, 
                     skip_header = 1, 
                     delimiter = ','
                    )
data

value_precipitations = precipitation(data)

In [46]:
#test_1_numpy.test_precipitation(value_precipitations)

In [47]:
no_rain = quant_days_no_rain(value_precipitations)
#test_1_numpy.test_quant_days_no_rain(no_rain)

In [48]:
with_rain = quant_days_with_rain(value_precipitations)
#test_1_numpy.test_quant_days_with_rain(with_rain)

In [49]:
with_rain_greater_100 = quant_days_vith_rain_greater_100(value_precipitations)
#test_1_numpy.test_quant_days_vith_rain_greater_100(with_rain_greater_100)

In [50]:
with_rain_LessEqual_100 = quant_days_vith_rain_LessEqual_100(value_precipitations)
#test_1_numpy.test_quant_days_vith_rain_LessEqual_100(with_rain_LessEqual_100)

## Versões

In [51]:
import numpy
numpy.version.version

'1.24.4'